var annotated_dup =
[
    [ "ChetoRp", "namespace_cheto_rp.html", [
      [ "Database", "namespace_cheto_rp_1_1_database.html", [
        [ "DbEntries", "class_cheto_rp_1_1_database_1_1_db_entries.html", "class_cheto_rp_1_1_database_1_1_db_entries" ],
        [ "DbEntryAttribute", "class_cheto_rp_1_1_database_1_1_db_entry_attribute.html", null ],
        [ "DbEntryIdAttribute", "class_cheto_rp_1_1_database_1_1_db_entry_id_attribute.html", null ],
        [ "DbTables", "class_cheto_rp_1_1_database_1_1_db_tables.html", "class_cheto_rp_1_1_database_1_1_db_tables" ],
        [ "DbTransaction", "class_cheto_rp_1_1_database_1_1_db_transaction.html", "class_cheto_rp_1_1_database_1_1_db_transaction" ]
      ] ],
      [ "Economy", "namespace_cheto_rp_1_1_economy.html", [
        [ "BankSystem", "class_cheto_rp_1_1_economy_1_1_bank_system.html", null ],
        [ "CashSystem", "class_cheto_rp_1_1_economy_1_1_cash_system.html", "class_cheto_rp_1_1_economy_1_1_cash_system" ],
        [ "EconomyConfig", "class_cheto_rp_1_1_economy_1_1_economy_config.html", null ],
        [ "EconomyModule", "class_cheto_rp_1_1_economy_1_1_economy_module.html", "class_cheto_rp_1_1_economy_1_1_economy_module" ],
        [ "ICashSystem", "interface_cheto_rp_1_1_economy_1_1_i_cash_system.html", "interface_cheto_rp_1_1_economy_1_1_i_cash_system" ]
      ] ],
      [ "Employment", "namespace_cheto_rp_1_1_employment.html", [
        [ "EmploymentModule", "class_cheto_rp_1_1_employment_1_1_employment_module.html", "class_cheto_rp_1_1_employment_1_1_employment_module" ],
        [ "EmploymentModuleConfig", "class_cheto_rp_1_1_employment_1_1_employment_module_config.html", "class_cheto_rp_1_1_employment_1_1_employment_module_config" ],
        [ "Team", "class_cheto_rp_1_1_employment_1_1_team.html", "class_cheto_rp_1_1_employment_1_1_team" ],
        [ "TeamChange", "class_cheto_rp_1_1_employment_1_1_team_change.html", "class_cheto_rp_1_1_employment_1_1_team_change" ],
        [ "TeamConfig", "class_cheto_rp_1_1_employment_1_1_team_config.html", "class_cheto_rp_1_1_employment_1_1_team_config" ]
      ] ],
      [ "Localization", "namespace_cheto_rp_1_1_localization.html", [
        [ "Locales", "namespace_cheto_rp_1_1_localization_1_1_locales.html", [
          [ "AmericanEnglish", "class_cheto_rp_1_1_localization_1_1_locales_1_1_american_english.html", "class_cheto_rp_1_1_localization_1_1_locales_1_1_american_english" ],
          [ "UruguayanSpanish", "class_cheto_rp_1_1_localization_1_1_locales_1_1_uruguayan_spanish.html", "class_cheto_rp_1_1_localization_1_1_locales_1_1_uruguayan_spanish" ]
        ] ],
        [ "ILocale", "interface_cheto_rp_1_1_localization_1_1_i_locale.html", "interface_cheto_rp_1_1_localization_1_1_i_locale" ],
        [ "ILocalizationData", "interface_cheto_rp_1_1_localization_1_1_i_localization_data.html", "interface_cheto_rp_1_1_localization_1_1_i_localization_data" ],
        [ "LocaleStringConverter", "class_cheto_rp_1_1_localization_1_1_locale_string_converter.html", "class_cheto_rp_1_1_localization_1_1_locale_string_converter" ],
        [ "LocaleStrings", "class_cheto_rp_1_1_localization_1_1_locale_strings.html", "class_cheto_rp_1_1_localization_1_1_locale_strings" ],
        [ "LocaleStringsPropertyAttribute", "class_cheto_rp_1_1_localization_1_1_locale_strings_property_attribute.html", null ],
        [ "LocalizationDataPropertyAttribute", "class_cheto_rp_1_1_localization_1_1_localization_data_property_attribute.html", null ],
        [ "LocalizationManager", "class_cheto_rp_1_1_localization_1_1_localization_manager.html", "class_cheto_rp_1_1_localization_1_1_localization_manager" ],
        [ "LocalizationModule", "class_cheto_rp_1_1_localization_1_1_localization_module.html", "class_cheto_rp_1_1_localization_1_1_localization_module" ],
        [ "LocalizationModuleConfig", "class_cheto_rp_1_1_localization_1_1_localization_module_config.html", "class_cheto_rp_1_1_localization_1_1_localization_module_config" ]
      ] ],
      [ "BaseModule", "class_cheto_rp_1_1_base_module.html", "class_cheto_rp_1_1_base_module" ],
      [ "BaseModuleConfig", "class_cheto_rp_1_1_base_module_config.html", "class_cheto_rp_1_1_base_module_config" ],
      [ "ChetoRpGame", "class_cheto_rp_1_1_cheto_rp_game.html", "class_cheto_rp_1_1_cheto_rp_game" ],
      [ "ConfigLocalizedPropertyAttribute", "class_cheto_rp_1_1_config_localized_property_attribute.html", null ],
      [ "GameConfigObjectAttribute", "class_cheto_rp_1_1_game_config_object_attribute.html", null ],
      [ "GameConfigOptionInfoAttribute", "class_cheto_rp_1_1_game_config_option_info_attribute.html", "class_cheto_rp_1_1_game_config_option_info_attribute" ],
      [ "GameEvents", "class_cheto_rp_1_1_game_events.html", "class_cheto_rp_1_1_game_events" ],
      [ "GameModuleAttribute", "class_cheto_rp_1_1_game_module_attribute.html", "class_cheto_rp_1_1_game_module_attribute" ],
      [ "GamePlayer", "class_cheto_rp_1_1_game_player.html", "class_cheto_rp_1_1_game_player" ],
      [ "GameWalkController", "class_cheto_rp_1_1_game_walk_controller.html", "class_cheto_rp_1_1_game_walk_controller" ],
      [ "IGamePlayer", "interface_cheto_rp_1_1_i_game_player.html", "interface_cheto_rp_1_1_i_game_player" ],
      [ "IOptionalConfigStore", "interface_cheto_rp_1_1_i_optional_config_store.html", "interface_cheto_rp_1_1_i_optional_config_store" ],
      [ "ModifiableDamageInfo", "class_cheto_rp_1_1_modifiable_damage_info.html", "class_cheto_rp_1_1_modifiable_damage_info" ],
      [ "Module", "class_cheto_rp_1_1_module.html", "class_cheto_rp_1_1_module" ],
      [ "Modules", "class_cheto_rp_1_1_modules.html", "class_cheto_rp_1_1_modules" ],
      [ "OptionalModule", "class_cheto_rp_1_1_optional_module.html", "class_cheto_rp_1_1_optional_module" ],
      [ "StringExtensions", "class_cheto_rp_1_1_string_extensions.html", "class_cheto_rp_1_1_string_extensions" ]
    ] ],
    [ "Sandbox", "namespace_sandbox.html", [
      [ "Tools", "namespace_sandbox_1_1_tools.html", [
        [ "BalloonTool", "class_sandbox_1_1_tools_1_1_balloon_tool.html", "class_sandbox_1_1_tools_1_1_balloon_tool" ],
        [ "BaseTool", "class_sandbox_1_1_tools_1_1_base_tool.html", "class_sandbox_1_1_tools_1_1_base_tool" ],
        [ "BoxShooter", "class_sandbox_1_1_tools_1_1_box_shooter.html", "class_sandbox_1_1_tools_1_1_box_shooter" ],
        [ "ColorTool", "class_sandbox_1_1_tools_1_1_color_tool.html", "class_sandbox_1_1_tools_1_1_color_tool" ],
        [ "LampTool", "class_sandbox_1_1_tools_1_1_lamp_tool.html", "class_sandbox_1_1_tools_1_1_lamp_tool" ],
        [ "LeafBlowerTool", "class_sandbox_1_1_tools_1_1_leaf_blower_tool.html", "class_sandbox_1_1_tools_1_1_leaf_blower_tool" ],
        [ "LightTool", "class_sandbox_1_1_tools_1_1_light_tool.html", "class_sandbox_1_1_tools_1_1_light_tool" ],
        [ "PreviewEntity", "class_sandbox_1_1_tools_1_1_preview_entity.html", "class_sandbox_1_1_tools_1_1_preview_entity" ],
        [ "RemoverTool", "class_sandbox_1_1_tools_1_1_remover_tool.html", "class_sandbox_1_1_tools_1_1_remover_tool" ],
        [ "ResizerTool", "class_sandbox_1_1_tools_1_1_resizer_tool.html", "class_sandbox_1_1_tools_1_1_resizer_tool" ],
        [ "RopeTool", "class_sandbox_1_1_tools_1_1_rope_tool.html", "class_sandbox_1_1_tools_1_1_rope_tool" ],
        [ "ThrusterTool", "class_sandbox_1_1_tools_1_1_thruster_tool.html", "class_sandbox_1_1_tools_1_1_thruster_tool" ],
        [ "WeldTool", "class_sandbox_1_1_tools_1_1_weld_tool.html", "class_sandbox_1_1_tools_1_1_weld_tool" ],
        [ "WheelTool", "class_sandbox_1_1_tools_1_1_wheel_tool.html", "class_sandbox_1_1_tools_1_1_wheel_tool" ]
      ] ],
      [ "CarAnimator", "class_sandbox_1_1_car_animator.html", "class_sandbox_1_1_car_animator" ]
    ] ],
    [ "BalloonEntity", "class_balloon_entity.html", "class_balloon_entity" ],
    [ "BouncyBallEntity", "class_bouncy_ball_entity.html", "class_bouncy_ball_entity" ],
    [ "CarCamera", "class_car_camera.html", "class_car_camera" ],
    [ "CarController", "class_car_controller.html", "class_car_controller" ],
    [ "CarEntity", "class_car_entity.html", "class_car_entity" ],
    [ "Carriable", "class_carriable.html", "class_carriable" ],
    [ "CarWheel", "struct_car_wheel.html", "struct_car_wheel" ],
    [ "CurrentTool", "class_current_tool.html", "class_current_tool" ],
    [ "DirectionalGravity", "class_directional_gravity.html", "class_directional_gravity" ],
    [ "DroneEntity", "class_drone_entity.html", "class_drone_entity" ],
    [ "EntityList", "class_entity_list.html", "class_entity_list" ],
    [ "Flashlight", "class_flashlight.html", "class_flashlight" ],
    [ "GravGun", "class_grav_gun.html", "class_grav_gun" ],
    [ "Health", "class_health.html", "class_health" ],
    [ "Inventory", "class_inventory.html", "class_inventory" ],
    [ "InventoryBar", "class_inventory_bar.html", "class_inventory_bar" ],
    [ "InventoryIcon", "class_inventory_icon.html", "class_inventory_icon" ],
    [ "LampEntity", "class_lamp_entity.html", "class_lamp_entity" ],
    [ "LightEntity", "class_light_entity.html", "class_light_entity" ],
    [ "NoiseTest", "class_noise_test.html", "class_noise_test" ],
    [ "PhysGun", "class_phys_gun.html", "class_phys_gun" ],
    [ "Pistol", "class_pistol.html", "class_pistol" ],
    [ "SandboxGame", "class_sandbox_game.html", "class_sandbox_game" ],
    [ "SandboxHud", "class_sandbox_hud.html", "class_sandbox_hud" ],
    [ "SandboxPlayer", "class_sandbox_player.html", "class_sandbox_player" ],
    [ "Shotgun", "class_shotgun.html", "class_shotgun" ],
    [ "SMG", "class_s_m_g.html", "class_s_m_g" ],
    [ "SpawnList", "class_spawn_list.html", "class_spawn_list" ],
    [ "SpawnMenu", "class_spawn_menu.html", "class_spawn_menu" ],
    [ "ThrusterEntity", "class_thruster_entity.html", "class_thruster_entity" ],
    [ "Tool", "class_tool.html", "class_tool" ],
    [ "ViewModel", "class_view_model.html", "class_view_model" ],
    [ "Weapon", "class_weapon.html", "class_weapon" ],
    [ "WheelEntity", "class_wheel_entity.html", "class_wheel_entity" ]
];